apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-router
  namespace: graphql-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-router
  template:
    metadata:
      labels:
        app: graphql-router
    spec:
      serviceAccountName: graphql-router
      imagePullSecrets:
        - name: graphql-router-zot-pull-secret
      containers:
        - name: graphql-router
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 4000
            - containerPort: 8088
