apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: graphql-router-zot-pull-secret
  namespace: graphql-router
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao
    kind: SecretStore
  target:
    name: graphql-router-zot-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {{`{"auths":{"registry.morrisons.site":{"username":"k8s-graphql-router","password":"{{ .password }}","auth":"{{ printf "k8s-graphql-router:%s" .password | b64enc }}"}}}`}}
  data:
    - secretKey: password
      remoteRef:
        key: homelab/service/k8s-zot/k8s-graphql-router/zot-pull
        property: value
